/**
 * Exact static backend operation inventory generated from accepted Phase 9 Step 281 evidence.
 *
 * `frontendAccessPolicy` is a conservative frontend policy. It does not assert
 * that static dependency analysis proved backend authorization. Backend
 * authorization remains authoritative for every request.
 */
export const API_METHODS = ["DELETE", "GET", "PATCH", "POST", "PUT"] as const;
export type ApiMethod = (typeof API_METHODS)[number];
export type FrontendAccessPolicy = "public" | "authenticated";

export interface BackendOperationDefinition {
  readonly key: string;
  readonly operationId: string | null;
  readonly method: ApiMethod;
  readonly pathTemplate: string;
  readonly pathParameters: readonly string[];
  readonly source: string;
  readonly sourceLine: number;
  readonly responseModel: string | null;
  readonly frontendAccessPolicy: FrontendAccessPolicy;
  readonly inventorySecurityDependencySignal: boolean;
}

export const BACKEND_OPERATIONS = Object.freeze([
  {"key":"get_root","operationId":null,"method":"GET","pathTemplate":"/","pathParameters":[],"source":"backend/app/main.py","sourceLine":219,"responseModel":null,"frontendAccessPolicy":"public","inventorySecurityDependencySignal":false},
  {"key":"assessAnalyzerApplication","operationId":"assessAnalyzerApplication","method":"POST","pathTemplate":"/api/v1/calculations/analyzers/application-assessment","pathParameters":[],"source":"backend/app/api/analyzers.py","sourceLine":311,"responseModel":"AnalyzerAssessmentEnvelope","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"getAnalyzerTechnologyCatalogue","operationId":"getAnalyzerTechnologyCatalogue","method":"GET","pathTemplate":"/api/v1/calculations/analyzers/catalogue","pathParameters":[],"source":"backend/app/api/analyzers.py","sourceLine":232,"responseModel":"AnalyzerCatalogueResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"listAnalyzerDesignCaseExamples","operationId":"listAnalyzerDesignCaseExamples","method":"GET","pathTemplate":"/api/v1/calculations/analyzers/design-case-examples","pathParameters":[],"source":"backend/app/api/analyzers.py","sourceLine":283,"responseModel":"AnalyzerDesignCaseExamplesResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"listAnalyzerKnowledgeLinks","operationId":"listAnalyzerKnowledgeLinks","method":"GET","pathTemplate":"/api/v1/calculations/analyzers/knowledge-links","pathParameters":[],"source":"backend/app/api/analyzers.py","sourceLine":257,"responseModel":"AnalyzerKnowledgeLinksResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"getControlValveCatalogue","operationId":"getControlValveCatalogue","method":"GET","pathTemplate":"/api/v1/calculations/control-valves/catalogue","pathParameters":[],"source":"backend/app/api/control_valves.py","sourceLine":256,"responseModel":"ControlValveCatalogueResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"evaluateControlValveDesignCase","operationId":"evaluateControlValveDesignCase","method":"POST","pathTemplate":"/api/v1/calculations/control-valves/design-cases/evaluate","pathParameters":[],"source":"backend/app/api/control_valves.py","sourceLine":349,"responseModel":"ControlValveDesignCaseOutcome","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"executeControlValveCalculation","operationId":"executeControlValveCalculation","method":"POST","pathTemplate":"/api/v1/calculations/control-valves/execute","pathParameters":[],"source":"backend/app/api/control_valves.py","sourceLine":313,"responseModel":"ControlValveExecutionOutcome","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"listControlValveKnowledgeLinks","operationId":"listControlValveKnowledgeLinks","method":"GET","pathTemplate":"/api/v1/calculations/control-valves/knowledge-links","pathParameters":[],"source":"backend/app/api/control_valves.py","sourceLine":283,"responseModel":"ControlValveKnowledgeLinksResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"assessDPFlowApplication","operationId":"assessDPFlowApplication","method":"POST","pathTemplate":"/api/v1/calculations/dp-flow/application-assessment","pathParameters":[],"source":"backend/app/api/dp_flow.py","sourceLine":433,"responseModel":"DPFlowApplicationAssessment","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"getDPFlowCatalogue","operationId":"getDPFlowCatalogue","method":"GET","pathTemplate":"/api/v1/calculations/dp-flow/catalogue","pathParameters":[],"source":"backend/app/api/dp_flow.py","sourceLine":332,"responseModel":"tuple[DPFlowMethodCatalogueEntry, ...]","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"listDPFlowDesignCaseExamples","operationId":"listDPFlowDesignCaseExamples","method":"GET","pathTemplate":"/api/v1/calculations/dp-flow/design-case-examples","pathParameters":[],"source":"backend/app/api/dp_flow.py","sourceLine":380,"responseModel":"tuple[DPFlowStoredDesignCaseExample, ...]","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"evaluateDPFlowDesignCase","operationId":"evaluateDPFlowDesignCase","method":"POST","pathTemplate":"/api/v1/calculations/dp-flow/design-cases/evaluate","pathParameters":[],"source":"backend/app/api/dp_flow.py","sourceLine":462,"responseModel":"DPFlowDesignCaseOutcome","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"evaluateStoredDPFlowDesignCase","operationId":"evaluateStoredDPFlowDesignCase","method":"POST","pathTemplate":"/api/v1/calculations/dp-flow/design-cases/stored/evaluate","pathParameters":[],"source":"backend/app/api/dp_flow.py","sourceLine":492,"responseModel":"DPFlowDesignCaseOutcome","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"executeDPFlowCalculation","operationId":"executeDPFlowCalculation","method":"POST","pathTemplate":"/api/v1/calculations/dp-flow/execute","pathParameters":[],"source":"backend/app/api/dp_flow.py","sourceLine":408,"responseModel":"DPFlowExecutionOutcome","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"listDPFlowKnowledgeLinks","operationId":"listDPFlowKnowledgeLinks","method":"GET","pathTemplate":"/api/v1/calculations/dp-flow/knowledge-links","pathParameters":[],"source":"backend/app/api/dp_flow.py","sourceLine":356,"responseModel":"tuple[DPFlowKnowledgeLink, ...]","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"executeCalculation","operationId":"executeCalculation","method":"POST","pathTemplate":"/api/v1/calculations/execute","pathParameters":[],"source":"backend/app/api/calculations.py","sourceLine":506,"responseModel":"CalculationExecutionResult","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"assessLevelApplication","operationId":"assessLevelApplication","method":"POST","pathTemplate":"/api/v1/calculations/level/application-assessment","pathParameters":[],"source":"backend/app/api/level_applications.py","sourceLine":198,"responseModel":"LevelApplicationAssessment","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"listCalculationMethods","operationId":"listCalculationMethods","method":"GET","pathTemplate":"/api/v1/calculations/methods","pathParameters":[],"source":"backend/app/api/calculations.py","sourceLine":389,"responseModel":"CalculationMethodCatalogue","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"getCalculationMethodDefinition","operationId":"getCalculationMethodDefinition","method":"GET","pathTemplate":"/api/v1/calculations/methods/definition","pathParameters":[],"source":"backend/app/api/calculations.py","sourceLine":460,"responseModel":"CalculationMethodMetadata","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"listCalculationMethodVersions","operationId":"listCalculationMethodVersions","method":"GET","pathTemplate":"/api/v1/calculations/methods/versions","pathParameters":[],"source":"backend/app/api/calculations.py","sourceLine":429,"responseModel":"CalculationMethodVersionCatalogue","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"getPressureReliefCatalogue","operationId":"getPressureReliefCatalogue","method":"GET","pathTemplate":"/api/v1/calculations/pressure-relief/catalogue","pathParameters":[],"source":"backend/app/api/pressure_relief.py","sourceLine":260,"responseModel":"PressureReliefCatalogueResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"executePressureReliefCalculation","operationId":"executePressureReliefCalculation","method":"POST","pathTemplate":"/api/v1/calculations/pressure-relief/execute","pathParameters":[],"source":"backend/app/api/pressure_relief.py","sourceLine":353,"responseModel":"PressureReliefExecutionOutcome","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"listPressureReliefKnowledgeLinks","operationId":"listPressureReliefKnowledgeLinks","method":"GET","pathTemplate":"/api/v1/calculations/pressure-relief/knowledge-links","pathParameters":[],"source":"backend/app/api/pressure_relief.py","sourceLine":287,"responseModel":"PressureReliefKnowledgeLinksResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"assessPressureReliefReadiness","operationId":"assessPressureReliefReadiness","method":"POST","pathTemplate":"/api/v1/calculations/pressure-relief/readiness-assessment","pathParameters":[],"source":"backend/app/api/pressure_relief.py","sourceLine":317,"responseModel":"PressureReliefReadinessAssessmentOutcome","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"getEngineeringRun","operationId":"getEngineeringRun","method":"GET","pathTemplate":"/api/v1/design-runs/{run_id}","pathParameters":["run_id"],"source":"backend/app/api/designs.py","sourceLine":567,"responseModel":"EngineeringRunRecord","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"listDesignCases","operationId":"listDesignCases","method":"GET","pathTemplate":"/api/v1/designs","pathParameters":[],"source":"backend/app/api/designs.py","sourceLine":375,"responseModel":"DesignCasePage","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"createDesignCase","operationId":"createDesignCase","method":"POST","pathTemplate":"/api/v1/designs","pathParameters":[],"source":"backend/app/api/designs.py","sourceLine":359,"responseModel":"DesignCaseRecord","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"getDesignCase","operationId":"getDesignCase","method":"GET","pathTemplate":"/api/v1/designs/{design_case_id}","pathParameters":["design_case_id"],"source":"backend/app/api/designs.py","sourceLine":396,"responseModel":"DesignCaseRecord","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"assessAndPersistDesignAnalyzerApplication","operationId":"assessAndPersistDesignAnalyzerApplication","method":"POST","pathTemplate":"/api/v1/designs/{design_case_id}/analyzer-assessments","pathParameters":["design_case_id"],"source":"backend/app/api/designs.py","sourceLine":521,"responseModel":"PersistedAnalyzerAssessment","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"executeAndPersistDesignCalculation","operationId":"executeAndPersistDesignCalculation","method":"POST","pathTemplate":"/api/v1/designs/{design_case_id}/calculations","pathParameters":["design_case_id"],"source":"backend/app/api/designs.py","sourceLine":495,"responseModel":"PersistedCalculationExecution","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"listDesignDatasheets","operationId":"listDesignDatasheets","method":"GET","pathTemplate":"/api/v1/designs/{design_case_id}/datasheets","pathParameters":["design_case_id"],"source":"backend/app/api/datasheets.py","sourceLine":293,"responseModel":"DatasheetPage","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"createDesignDatasheet","operationId":"createDesignDatasheet","method":"POST","pathTemplate":"/api/v1/designs/{design_case_id}/datasheets","pathParameters":["design_case_id"],"source":"backend/app/api/datasheets.py","sourceLine":273,"responseModel":"PersistedDatasheetRecord","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"getDesignDatasheet","operationId":"getDesignDatasheet","method":"GET","pathTemplate":"/api/v1/designs/{design_case_id}/datasheets/{datasheet_id}","pathParameters":["design_case_id","datasheet_id"],"source":"backend/app/api/datasheets.py","sourceLine":315,"responseModel":"PersistedDatasheetRecord","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"listDesignDatasheetRevisions","operationId":"listDesignDatasheetRevisions","method":"GET","pathTemplate":"/api/v1/designs/{design_case_id}/datasheets/{datasheet_id}/revisions","pathParameters":["design_case_id","datasheet_id"],"source":"backend/app/api/datasheets.py","sourceLine":362,"responseModel":"DatasheetRevisionPage","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"reviseDesignDatasheet","operationId":"reviseDesignDatasheet","method":"POST","pathTemplate":"/api/v1/designs/{design_case_id}/datasheets/{datasheet_id}/revisions","pathParameters":["design_case_id","datasheet_id"],"source":"backend/app/api/datasheets.py","sourceLine":341,"responseModel":"PersistedDatasheetRecord","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"getDesignDatasheetRevision","operationId":"getDesignDatasheetRevision","method":"GET","pathTemplate":"/api/v1/designs/{design_case_id}/datasheets/{datasheet_id}/revisions/{revision_number}","pathParameters":["design_case_id","datasheet_id","revision_number"],"source":"backend/app/api/datasheets.py","sourceLine":390,"responseModel":"PersistedDatasheetRevision","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"downloadDesignDatasheetRevision","operationId":"downloadDesignDatasheetRevision","method":"GET","pathTemplate":"/api/v1/designs/{design_case_id}/datasheets/{datasheet_id}/revisions/{revision_number}/exports/{export_format}","pathParameters":["design_case_id","datasheet_id","revision_number","export_format"],"source":"backend/app/api/datasheets.py","sourceLine":428,"responseModel":null,"frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"listDesignCaseRevisions","operationId":"listDesignCaseRevisions","method":"GET","pathTemplate":"/api/v1/designs/{design_case_id}/revisions","pathParameters":["design_case_id"],"source":"backend/app/api/designs.py","sourceLine":441,"responseModel":"DesignRevisionPage","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"reviseDesignCase","operationId":"reviseDesignCase","method":"POST","pathTemplate":"/api/v1/designs/{design_case_id}/revisions","pathParameters":["design_case_id"],"source":"backend/app/api/designs.py","sourceLine":421,"responseModel":"DesignCaseRecord","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"getDesignCaseRevision","operationId":"getDesignCaseRevision","method":"GET","pathTemplate":"/api/v1/designs/{design_case_id}/revisions/{revision_number}","pathParameters":["design_case_id","revision_number"],"source":"backend/app/api/designs.py","sourceLine":467,"responseModel":"DesignCaseRevisionRecord","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"listDesignEngineeringRuns","operationId":"listDesignEngineeringRuns","method":"GET","pathTemplate":"/api/v1/designs/{design_case_id}/runs","pathParameters":["design_case_id"],"source":"backend/app/api/designs.py","sourceLine":541,"responseModel":"EngineeringRunPage","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_ingestion_jobs","operationId":null,"method":"POST","pathTemplate":"/api/v1/ingestion/jobs","pathParameters":[],"source":"backend/app/api/ingestion.py","sourceLine":244,"responseModel":"IngestionJob","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_ingestion_jobs_search","operationId":null,"method":"POST","pathTemplate":"/api/v1/ingestion/jobs/search","pathParameters":[],"source":"backend/app/api/ingestion.py","sourceLine":284,"responseModel":"IngestionJobQueryResult","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_ingestion_jobs_job_id","operationId":null,"method":"GET","pathTemplate":"/api/v1/ingestion/jobs/{job_id}","pathParameters":["job_id"],"source":"backend/app/api/ingestion.py","sourceLine":316,"responseModel":"IngestionJob","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_ingestion_jobs_job_id_cancel","operationId":null,"method":"POST","pathTemplate":"/api/v1/ingestion/jobs/{job_id}/cancel","pathParameters":["job_id"],"source":"backend/app/api/ingestion.py","sourceLine":386,"responseModel":"IngestionJob","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_ingestion_jobs_job_id_cancellation_request","operationId":null,"method":"POST","pathTemplate":"/api/v1/ingestion/jobs/{job_id}/cancellation-request","pathParameters":["job_id"],"source":"backend/app/api/ingestion.py","sourceLine":369,"responseModel":"IngestionJob","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_ingestion_jobs_job_id_documents_document_id_retry","operationId":null,"method":"POST","pathTemplate":"/api/v1/ingestion/jobs/{job_id}/documents/{document_id}/retry","pathParameters":["job_id","document_id"],"source":"backend/app/api/ingestion.py","sourceLine":420,"responseModel":"IngestionJob","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_ingestion_jobs_job_id_execute","operationId":null,"method":"POST","pathTemplate":"/api/v1/ingestion/jobs/{job_id}/execute","pathParameters":["job_id"],"source":"backend/app/api/filesystem_document_execution_api.py","sourceLine":193,"responseModel":"IngestionJob","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_ingestion_jobs_job_id_queue","operationId":null,"method":"POST","pathTemplate":"/api/v1/ingestion/jobs/{job_id}/queue","pathParameters":["job_id"],"source":"backend/app/api/ingestion.py","sourceLine":333,"responseModel":"IngestionJob","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_ingestion_jobs_job_id_retry","operationId":null,"method":"POST","pathTemplate":"/api/v1/ingestion/jobs/{job_id}/retry","pathParameters":["job_id"],"source":"backend/app/api/ingestion.py","sourceLine":403,"responseModel":"IngestionJob","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_ingestion_jobs_job_id_start","operationId":null,"method":"POST","pathTemplate":"/api/v1/ingestion/jobs/{job_id}/start","pathParameters":["job_id"],"source":"backend/app/api/ingestion.py","sourceLine":350,"responseModel":"IngestionJob","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_ingestion_statistics","operationId":null,"method":"GET","pathTemplate":"/api/v1/ingestion/statistics","pathParameters":[],"source":"backend/app/api/ingestion.py","sourceLine":227,"responseModel":"IngestionJobStatistics","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_ingestion_uploads","operationId":null,"method":"POST","pathTemplate":"/api/v1/ingestion/uploads","pathParameters":[],"source":"backend/app/api/filesystem_document_upload_api.py","sourceLine":639,"responseModel":"IngestionJob","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_knowledge","operationId":null,"method":"GET","pathTemplate":"/api/v1/knowledge","pathParameters":[],"source":"backend/app/api/knowledge.py","sourceLine":313,"responseModel":"list[EngineeringKnowledge]","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_knowledge","operationId":null,"method":"POST","pathTemplate":"/api/v1/knowledge","pathParameters":[],"source":"backend/app/api/knowledge.py","sourceLine":332,"responseModel":"EngineeringKnowledge","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"put_api_v1_knowledge","operationId":null,"method":"PUT","pathTemplate":"/api/v1/knowledge","pathParameters":[],"source":"backend/app/api/knowledge.py","sourceLine":349,"responseModel":"EngineeringKnowledge","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_knowledge_publication_readiness","operationId":null,"method":"POST","pathTemplate":"/api/v1/knowledge/publication-readiness","pathParameters":[],"source":"backend/app/api/knowledge.py","sourceLine":300,"responseModel":"PublicationReadiness","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_knowledge_search","operationId":null,"method":"POST","pathTemplate":"/api/v1/knowledge/search","pathParameters":[],"source":"backend/app/api/knowledge.py","sourceLine":232,"responseModel":"list[KnowledgeSearchResult]","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_knowledge_search_safety","operationId":null,"method":"POST","pathTemplate":"/api/v1/knowledge/search/safety","pathParameters":[],"source":"backend/app/api/knowledge.py","sourceLine":262,"responseModel":"list[KnowledgeSearchResult]","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_knowledge_search_text","operationId":null,"method":"POST","pathTemplate":"/api/v1/knowledge/search/text","pathParameters":[],"source":"backend/app/api/knowledge.py","sourceLine":245,"responseModel":"list[KnowledgeSearchResult]","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_knowledge_search_verified","operationId":null,"method":"POST","pathTemplate":"/api/v1/knowledge/search/verified","pathParameters":[],"source":"backend/app/api/knowledge.py","sourceLine":281,"responseModel":"list[KnowledgeSearchResult]","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_knowledge_statistics","operationId":null,"method":"GET","pathTemplate":"/api/v1/knowledge/statistics","pathParameters":[],"source":"backend/app/api/knowledge.py","sourceLine":202,"responseModel":"KnowledgeServiceStatistics","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_knowledge_summaries","operationId":null,"method":"GET","pathTemplate":"/api/v1/knowledge/summaries","pathParameters":[],"source":"backend/app/api/knowledge.py","sourceLine":214,"responseModel":"list[KnowledgeSummary]","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"delete_api_v1_knowledge_knowledge_id","operationId":null,"method":"DELETE","pathTemplate":"/api/v1/knowledge/{knowledge_id}","pathParameters":["knowledge_id"],"source":"backend/app/api/knowledge.py","sourceLine":487,"responseModel":null,"frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_knowledge_knowledge_id","operationId":null,"method":"GET","pathTemplate":"/api/v1/knowledge/{knowledge_id}","pathParameters":["knowledge_id"],"source":"backend/app/api/knowledge.py","sourceLine":436,"responseModel":"EngineeringKnowledge","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"put_api_v1_knowledge_knowledge_id","operationId":null,"method":"PUT","pathTemplate":"/api/v1/knowledge/{knowledge_id}","pathParameters":["knowledge_id"],"source":"backend/app/api/knowledge.py","sourceLine":460,"responseModel":"EngineeringKnowledge","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_knowledge_knowledge_id_history","operationId":null,"method":"GET","pathTemplate":"/api/v1/knowledge/{knowledge_id}/history","pathParameters":["knowledge_id"],"source":"backend/app/api/knowledge.py","sourceLine":390,"responseModel":"list[EngineeringKnowledge]","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_knowledge_knowledge_id_publication_readiness","operationId":null,"method":"GET","pathTemplate":"/api/v1/knowledge/{knowledge_id}/publication-readiness","pathParameters":["knowledge_id"],"source":"backend/app/api/knowledge.py","sourceLine":411,"responseModel":"PublicationReadiness","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_knowledge_knowledge_id_summary","operationId":null,"method":"GET","pathTemplate":"/api/v1/knowledge/{knowledge_id}/summary","pathParameters":["knowledge_id"],"source":"backend/app/api/knowledge.py","sourceLine":366,"responseModel":"KnowledgeSummary","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_manufacturers","operationId":null,"method":"GET","pathTemplate":"/api/v1/manufacturers","pathParameters":[],"source":"backend/app/api/manufacturers.py","sourceLine":23,"responseModel":"list[ManufacturerResponse]","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_manufacturers","operationId":null,"method":"POST","pathTemplate":"/api/v1/manufacturers","pathParameters":[],"source":"backend/app/api/manufacturers.py","sourceLine":48,"responseModel":"ManufacturerResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"delete_api_v1_manufacturers_manufacturer_id","operationId":null,"method":"DELETE","pathTemplate":"/api/v1/manufacturers/{manufacturer_id}","pathParameters":["manufacturer_id"],"source":"backend/app/api/manufacturers.py","sourceLine":78,"responseModel":null,"frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_manufacturers_manufacturer_id","operationId":null,"method":"GET","pathTemplate":"/api/v1/manufacturers/{manufacturer_id}","pathParameters":["manufacturer_id"],"source":"backend/app/api/manufacturers.py","sourceLine":33,"responseModel":"ManufacturerResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"patch_api_v1_manufacturers_manufacturer_id","operationId":null,"method":"PATCH","pathTemplate":"/api/v1/manufacturers/{manufacturer_id}","pathParameters":["manufacturer_id"],"source":"backend/app/api/manufacturers.py","sourceLine":62,"responseModel":"ManufacturerResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_measurements","operationId":null,"method":"GET","pathTemplate":"/api/v1/measurements","pathParameters":[],"source":"backend/app/api/measurements.py","sourceLine":10,"responseModel":null,"frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_product_families","operationId":null,"method":"GET","pathTemplate":"/api/v1/product-families","pathParameters":[],"source":"backend/app/api/product_families.py","sourceLine":24,"responseModel":"list[ProductFamilyResponse]","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_product_families","operationId":null,"method":"POST","pathTemplate":"/api/v1/product-families","pathParameters":[],"source":"backend/app/api/product_families.py","sourceLine":56,"responseModel":"ProductFamilyResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"delete_api_v1_product_families_product_family_id","operationId":null,"method":"DELETE","pathTemplate":"/api/v1/product-families/{product_family_id}","pathParameters":["product_family_id"],"source":"backend/app/api/product_families.py","sourceLine":86,"responseModel":null,"frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_product_families_product_family_id","operationId":null,"method":"GET","pathTemplate":"/api/v1/product-families/{product_family_id}","pathParameters":["product_family_id"],"source":"backend/app/api/product_families.py","sourceLine":41,"responseModel":"ProductFamilyResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"patch_api_v1_product_families_product_family_id","operationId":null,"method":"PATCH","pathTemplate":"/api/v1/product-families/{product_family_id}","pathParameters":["product_family_id"],"source":"backend/app/api/product_families.py","sourceLine":70,"responseModel":"ProductFamilyResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_products","operationId":null,"method":"GET","pathTemplate":"/api/v1/products","pathParameters":[],"source":"backend/app/api/products.py","sourceLine":24,"responseModel":"list[ProductResponse]","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_products","operationId":null,"method":"POST","pathTemplate":"/api/v1/products","pathParameters":[],"source":"backend/app/api/products.py","sourceLine":81,"responseModel":"ProductResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"delete_api_v1_products_product_id","operationId":null,"method":"DELETE","pathTemplate":"/api/v1/products/{product_id}","pathParameters":["product_id"],"source":"backend/app/api/products.py","sourceLine":111,"responseModel":null,"frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_products_product_id","operationId":null,"method":"GET","pathTemplate":"/api/v1/products/{product_id}","pathParameters":["product_id"],"source":"backend/app/api/products.py","sourceLine":66,"responseModel":"ProductResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"patch_api_v1_products_product_id","operationId":null,"method":"PATCH","pathTemplate":"/api/v1/products/{product_id}","pathParameters":["product_id"],"source":"backend/app/api/products.py","sourceLine":95,"responseModel":"ProductResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_protocols","operationId":null,"method":"GET","pathTemplate":"/api/v1/protocols","pathParameters":[],"source":"backend/app/api/protocol.py","sourceLine":35,"responseModel":"list[ProtocolResponse]","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_protocols","operationId":null,"method":"POST","pathTemplate":"/api/v1/protocols","pathParameters":[],"source":"backend/app/api/protocol.py","sourceLine":73,"responseModel":"ProtocolResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"delete_api_v1_protocols_protocol_id","operationId":null,"method":"DELETE","pathTemplate":"/api/v1/protocols/{protocol_id}","pathParameters":["protocol_id"],"source":"backend/app/api/protocol.py","sourceLine":103,"responseModel":null,"frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_api_v1_protocols_protocol_id","operationId":null,"method":"GET","pathTemplate":"/api/v1/protocols/{protocol_id}","pathParameters":["protocol_id"],"source":"backend/app/api/protocol.py","sourceLine":58,"responseModel":"ProtocolResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"patch_api_v1_protocols_protocol_id","operationId":null,"method":"PATCH","pathTemplate":"/api/v1/protocols/{protocol_id}","pathParameters":["protocol_id"],"source":"backend/app/api/protocol.py","sourceLine":87,"responseModel":"ProtocolResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"post_api_v1_selections","operationId":null,"method":"POST","pathTemplate":"/api/v1/selections","pathParameters":[],"source":"backend/app/api/selections.py","sourceLine":21,"responseModel":"SelectionResponse","frontendAccessPolicy":"authenticated","inventorySecurityDependencySignal":false},
  {"key":"get_health","operationId":null,"method":"GET","pathTemplate":"/health","pathParameters":[],"source":"backend/app/main.py","sourceLine":220,"responseModel":null,"frontendAccessPolicy":"public","inventorySecurityDependencySignal":false},
] as const satisfies readonly BackendOperationDefinition[]);

const operationByKey: Readonly<Record<string, BackendOperationDefinition>> =
  Object.freeze(
    Object.fromEntries(
      BACKEND_OPERATIONS.map((operation) => [operation.key, operation]),
    ),
  );

export function getBackendOperation(key: string): BackendOperationDefinition {
  const operation = operationByKey[key];
  if (!operation) {
    throw new Error(`Unknown Engineer4Me backend operation: ${key}`);
  }
  return operation;
}
