"""link products to measurements

Revision ID: 4e428e4296af
Revises: 4b9e859f4b96
Create Date: 2026-07-16 12:20:21.615614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e428e4296af'
down_revision: Union[str, Sequence[str], None] = '4b9e859f4b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('measurement_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'measurements', ['measurement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'measurement_id')
    # ### end Alembic commands ###
