"""add engineering fields to products

Revision ID: 52d471b01be1
Revises: e2d8a11c6a91
Create Date: 2026-07-25 09:56:31.977571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d471b01be1'
down_revision: Union[str, Sequence[str], None] = 'e2d8a11c6a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('manufacturers_name_key'), 'manufacturers', type_='unique')
    op.create_index(op.f('ix_manufacturers_name'), 'manufacturers', ['name'], unique=True)
    op.alter_column('product_families', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_index(op.f('ix_product_families_manufacturer_id'), 'product_families', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_product_families_name'), 'product_families', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_families_name'), table_name='product_families')
    op.drop_index(op.f('ix_product_families_manufacturer_id'), table_name='product_families')
    op.alter_column('product_families', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_manufacturers_name'), table_name='manufacturers')
    op.create_unique_constraint(op.f('manufacturers_name_key'), 'manufacturers', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
