"""equipment and faults redesign

Revision ID: 77a2673afe68
Revises: e393c563d100
Create Date: 2026-07-16 18:27:10.825051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a2673afe68'
down_revision: Union[str, Sequence[str], None] = 'e393c563d100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fault_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.ForeignKeyConstraint(['fault_id'], ['faults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('faults', sa.Column('equipment_id', sa.Integer(), nullable=True))
    op.add_column('faults', sa.Column('description', sa.String(length=500), nullable=True))
    op.drop_constraint(op.f('faults_product_id_fkey'), 'faults', type_='foreignkey')
    op.create_foreign_key(None, 'faults', 'equipment', ['equipment_id'], ['id'])
    op.drop_column('faults', 'title')
    op.drop_column('faults', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faults', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('faults', sa.Column('title', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'faults', type_='foreignkey')
    op.create_foreign_key(op.f('faults_product_id_fkey'), 'faults', 'products', ['product_id'], ['id'])
    op.alter_column('faults', 'symptom',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('faults', 'description')
    op.drop_column('faults', 'equipment_id')
    op.drop_table('solutions')
    op.drop_table('equipment')
    # ### end Alembic commands ###
