"""link products to product families

Revision ID: f95655e40e78
Revises: 83dfcb429236
Create Date: 2026-07-16 13:13:13.033248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95655e40e78'
down_revision: Union[str, Sequence[str], None] = '83dfcb429236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('family_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'product_families', ['family_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'family_id')
    # ### end Alembic commands ###
