"""remove obsolete fault columns

Revision ID: f97ed5f3f201
Revises: 77a2673afe68
Create Date: 2026-07-16 19:02:04.882295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97ed5f3f201'
down_revision: Union[str, Sequence[str], None] = '77a2673afe68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faults', 'equipment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('faults', 'symptom',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('faults', 'corrective_action')
    op.drop_column('faults', 'probable_cause')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faults', sa.Column('probable_cause', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('faults', sa.Column('corrective_action', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.alter_column('faults', 'symptom',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('faults', 'equipment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
