"""Engineer4Me Phase 7 engineering-design package.

Step 89 establishes the import-safe package boundary. Step 96 adds the strict,
vendor-neutral level-application domain used by the reviewed assessment
wizard. Step 98 adds vendor-neutral DP primary-element screening with explicit
owned-product notices. Step 99 adds typed, immutable DP-flow workflow and
illustrative replay-case contracts. Step 106 adds strict analyzer application
models and a deterministic, vendor-neutral technology assistant. Step 107
binds analyzer assessments to inert internal governance metadata and adds
immutable illustrative design cases. User-created design-case persistence,
controlled datasheets, and export services are introduced by later reviewed
Phase 7 steps.

Voice input, speech recognition, voice search, and text-to-speech are not part
of this package. Those capabilities remain scheduled for Phase 10.
"""

from __future__ import annotations

from app.engineering.design.analyzer_assistant import (
    ANALYZER_ASSISTANT_VERSION,
    ANALYZER_RULESET_VERSION,
    ANALYZER_TECHNOLOGY_CATALOGUE,
    ANALYZER_TECHNOLOGY_REGISTRY,
    ANALYZER_TECHNOLOGY_TAXONOMY_VERSION,
    ANALYZER_VERIFICATION_STEPS,
    DEFAULT_ANALYZER_APPLICATION_ASSISTANT,
    AnalyzerApplicationAssistant,
    AnalyzerApplicationAssistantError,
    assess_analyzer_application,
)
from app.engineering.design.analyzer_models import (
    ANALYZER_APPLICATION_MODEL_VERSION,
    AnalyzerAnalyteFamily,
    AnalyzerAnalyteRequirement,
    AnalyzerApplicationAssessment,
    AnalyzerApplicationKind,
    AnalyzerApplicationRequest,
    AnalyzerConditionSeverity,
    AnalyzerConfidenceBand,
    AnalyzerEnvironmentCondition,
    AnalyzerInstallationContext,
    AnalyzerInterferenceMechanism,
    AnalyzerKnownInterference,
    AnalyzerMeasurementObjective,
    AnalyzerMeasurementRequirements,
    AnalyzerMissingInformation,
    AnalyzerProcessContext,
    AnalyzerResponseContributorKind,
    AnalyzerResponseTimeContributor,
    AnalyzerRuleResult,
    AnalyzerRuleStatus,
    AnalyzerSafetyContext,
    AnalyzerSafetyFinding,
    AnalyzerSampleApproach,
    AnalyzerSampleDisposition,
    AnalyzerSamplePhase,
    AnalyzerSampleSystemContext,
    AnalyzerScenarioDisposition,
    AnalyzerTechnology,
    AnalyzerTechnologyDefinition,
    AnalyzerTechnologyScenario,
    AnalyzerTriState,
    AnalyzerUnitText,
    AnalyzerUtility,
    AnalyzerVerificationPriority,
    AnalyzerVerificationStep,
    analyzer_confidence_band,
    canonical_analyzer_quantity_value,
    fingerprint_analyzer_payload,
)
from app.engineering.design.analyzer_workflow_models import (
    ANALYZER_DESIGN_CASE_EXAMPLES,
    ANALYZER_DESIGN_CASE_REGISTRY,
    ANALYZER_KNOWLEDGE_LINKS,
    ANALYZER_KNOWLEDGE_REGISTRY,
    ANALYZER_WORKFLOW_VERSION,
    AnalyzerAssessmentEnvelope,
    AnalyzerDesignCaseExample,
    AnalyzerExpectedScenario,
    AnalyzerKnowledgeLink,
    build_analyzer_example_fingerprint,
    build_analyzer_integration_fingerprint,
    resolve_analyzer_knowledge_links,
    validate_analyzer_design_case_example,
)
from app.engineering.design.dp_flow_application_models import (
    DP_FLOW_APPLICATION_MODEL_VERSION,
    FINAL_BRAND_DECISION_NOTICE,
    DPCalculationReadiness,
    DPConfidenceBand,
    DPFlowApplicationAssessment,
    DPFlowApplicationRequest,
    DPFluidPhase,
    DPMeasurementObjective,
    DPOfficialSource,
    DPOwnershipType,
    DPPressureLossClass,
    DPPrimaryElementDefinition,
    DPPrimaryElementFamily,
    DPPrimaryElementScenario,
    DPProprietaryNotice,
    DPScenarioDisposition,
    DPTriState,
    DPVerificationPriority,
    DPVerificationStep,
)
from app.engineering.design.dp_flow_application_wizard import (
    DEFAULT_DP_FLOW_APPLICATION_WIZARD,
    DP_FLOW_APPLICATION_RULESET_VERSION,
    DP_FLOW_APPLICATION_WIZARD_VERSION,
    GENERIC_PRIMARY_ELEMENTS,
    OFFICIAL_SOURCES,
    PRIMARY_ELEMENT_CATALOGUE,
    PROPRIETARY_PRIMARY_ELEMENTS,
    VERIFICATION_STEPS,
    DPFlowApplicationWizard,
    assess_dp_flow_application,
)
from app.engineering.design.level_application_models import (
    LEVEL_APPLICATION_MODEL_VERSION,
    SUPPORTED_LEVEL_CALCULATION_METHOD_IDS,
    SUPPORTED_LEVEL_METHOD_IDS,
    ApprovalText,
    LevelApplicationAssessment,
    LevelApplicationRequest,
    LevelConditionSeverity,
    LevelConfidenceBand,
    LevelContactPreference,
    LevelDpArrangement,
    LevelEnvironmentCondition,
    LevelIndustrySector,
    LevelInstallationContext,
    LevelMaintenanceAccess,
    LevelMeasurementObjective,
    LevelMeasurementRequirements,
    LevelMissingInformation,
    LevelMountingPosition,
    LevelProcessContext,
    LevelProcessPhase,
    LevelProtectionFunction,
    LevelRuleStatus,
    LevelSafetyContext,
    LevelScenarioDisposition,
    LevelScenarioRuleResult,
    LevelTechnology,
    LevelTechnologyScenario,
    LevelTriState,
    LevelVaporBehavior,
    LevelVerificationPriority,
    LevelVerificationStep,
    LevelVesselConfiguration,
    LevelVesselContext,
    LevelVesselGeometry,
    LevelWizardFinding,
    canonical_quantity_value,
)
from app.engineering.design.level_application_wizard import (
    DEFAULT_LEVEL_APPLICATION_WIZARD,
    LEVEL_APPLICATION_RULESET_VERSION,
    LEVEL_APPLICATION_WIZARD_VERSION,
    LevelApplicationWizard,
    LevelApplicationWizardError,
    assess_level_application,
)

PHASE_NUMBER = 7
PACKAGE_NAME = "engineering_design"
FOUNDATION_VERSION = "0.2.0"
VOICE_FUNCTIONALITY_ENABLED = False


__all__ = [
    "ANALYZER_APPLICATION_MODEL_VERSION",
    "ANALYZER_ASSISTANT_VERSION",
    "ANALYZER_DESIGN_CASE_EXAMPLES",
    "ANALYZER_DESIGN_CASE_REGISTRY",
    "ANALYZER_KNOWLEDGE_LINKS",
    "ANALYZER_KNOWLEDGE_REGISTRY",
    "ANALYZER_RULESET_VERSION",
    "ANALYZER_TECHNOLOGY_CATALOGUE",
    "ANALYZER_TECHNOLOGY_REGISTRY",
    "ANALYZER_TECHNOLOGY_TAXONOMY_VERSION",
    "ANALYZER_VERIFICATION_STEPS",
    "ANALYZER_WORKFLOW_VERSION",
    "DEFAULT_ANALYZER_APPLICATION_ASSISTANT",
    "DEFAULT_DP_FLOW_APPLICATION_WIZARD",
    "DEFAULT_LEVEL_APPLICATION_WIZARD",
    "DP_FLOW_APPLICATION_MODEL_VERSION",
    "DP_FLOW_APPLICATION_RULESET_VERSION",
    "DP_FLOW_APPLICATION_WIZARD_VERSION",
    "FINAL_BRAND_DECISION_NOTICE",
    "FOUNDATION_VERSION",
    "GENERIC_PRIMARY_ELEMENTS",
    "LEVEL_APPLICATION_MODEL_VERSION",
    "LEVEL_APPLICATION_RULESET_VERSION",
    "LEVEL_APPLICATION_WIZARD_VERSION",
    "OFFICIAL_SOURCES",
    "PACKAGE_NAME",
    "PHASE_NUMBER",
    "PRIMARY_ELEMENT_CATALOGUE",
    "PROPRIETARY_PRIMARY_ELEMENTS",
    "SUPPORTED_LEVEL_CALCULATION_METHOD_IDS",
    "SUPPORTED_LEVEL_METHOD_IDS",
    "VERIFICATION_STEPS",
    "VOICE_FUNCTIONALITY_ENABLED",
    "AnalyzerAnalyteFamily",
    "AnalyzerAnalyteRequirement",
    "AnalyzerApplicationAssessment",
    "AnalyzerApplicationAssistant",
    "AnalyzerApplicationAssistantError",
    "AnalyzerApplicationKind",
    "AnalyzerApplicationRequest",
    "AnalyzerAssessmentEnvelope",
    "AnalyzerConditionSeverity",
    "AnalyzerConfidenceBand",
    "AnalyzerDesignCaseExample",
    "AnalyzerEnvironmentCondition",
    "AnalyzerExpectedScenario",
    "AnalyzerInstallationContext",
    "AnalyzerInterferenceMechanism",
    "AnalyzerKnowledgeLink",
    "AnalyzerKnownInterference",
    "AnalyzerMeasurementObjective",
    "AnalyzerMeasurementRequirements",
    "AnalyzerMissingInformation",
    "AnalyzerProcessContext",
    "AnalyzerResponseContributorKind",
    "AnalyzerResponseTimeContributor",
    "AnalyzerRuleResult",
    "AnalyzerRuleStatus",
    "AnalyzerSafetyContext",
    "AnalyzerSafetyFinding",
    "AnalyzerSampleApproach",
    "AnalyzerSampleDisposition",
    "AnalyzerSamplePhase",
    "AnalyzerSampleSystemContext",
    "AnalyzerScenarioDisposition",
    "AnalyzerTechnology",
    "AnalyzerTechnologyDefinition",
    "AnalyzerTechnologyScenario",
    "AnalyzerTriState",
    "AnalyzerUnitText",
    "AnalyzerUtility",
    "AnalyzerVerificationPriority",
    "AnalyzerVerificationStep",
    "ApprovalText",
    "DPCalculationReadiness",
    "DPConfidenceBand",
    "DPFlowApplicationAssessment",
    "DPFlowApplicationRequest",
    "DPFlowApplicationWizard",
    "DPFluidPhase",
    "DPMeasurementObjective",
    "DPOfficialSource",
    "DPOwnershipType",
    "DPPressureLossClass",
    "DPPrimaryElementDefinition",
    "DPPrimaryElementFamily",
    "DPPrimaryElementScenario",
    "DPProprietaryNotice",
    "DPScenarioDisposition",
    "DPTriState",
    "DPVerificationPriority",
    "DPVerificationStep",
    "LevelApplicationAssessment",
    "LevelApplicationRequest",
    "LevelApplicationWizard",
    "LevelApplicationWizardError",
    "LevelConditionSeverity",
    "LevelConfidenceBand",
    "LevelContactPreference",
    "LevelDpArrangement",
    "LevelEnvironmentCondition",
    "LevelIndustrySector",
    "LevelInstallationContext",
    "LevelMaintenanceAccess",
    "LevelMeasurementObjective",
    "LevelMeasurementRequirements",
    "LevelMissingInformation",
    "LevelMountingPosition",
    "LevelProcessContext",
    "LevelProcessPhase",
    "LevelProtectionFunction",
    "LevelRuleStatus",
    "LevelSafetyContext",
    "LevelScenarioDisposition",
    "LevelScenarioRuleResult",
    "LevelTechnology",
    "LevelTechnologyScenario",
    "LevelTriState",
    "LevelVaporBehavior",
    "LevelVerificationPriority",
    "LevelVerificationStep",
    "LevelVesselConfiguration",
    "LevelVesselContext",
    "LevelVesselGeometry",
    "LevelWizardFinding",
    "analyzer_confidence_band",
    "assess_analyzer_application",
    "assess_dp_flow_application",
    "assess_level_application",
    "build_analyzer_example_fingerprint",
    "build_analyzer_integration_fingerprint",
    "canonical_analyzer_quantity_value",
    "canonical_quantity_value",
    "fingerprint_analyzer_payload",
    "resolve_analyzer_knowledge_links",
    "validate_analyzer_design_case_example",
]
